name: Default Profile for Well Architected Review
description: |
  This is the default profile for the Well Architected Review. It includes a set of checks that are
  recommended for all AWS accounts. You can customize this profile by adding or removing checks as needed.
checks:
  - cloudformation_stacks_termination_protection_enabled
  - dynamodb_tables_pitr_enabled
  - elb_logging_enabled
  - opensearch_service_domains_audit_logging_enabled
  - opensearch_service_domains_cloudwatch_logging_enabled
  - rds_instance_backup_enabled
  - rds_instance_deletion_protection
  - rds_instance_enhanced_monitoring_enabled
  - rds_instance_integration_cloudwatch_logs
  - rds_instance_multi_az
  # - apigateway_restapi_logging_enabled
  # - apigatewayv2_api_access_logging_enabled
  # - awslambda_function_invoke_api_operations_cloudtrail_logging_enabled
  # - cloudtrail_cloudwatch_logging_enabled
